### ISSUE TITLE
`json` macro requires `json_internal` macro to function

### ISSUE THREAD

**Issue by euclio** [serde-rs/json#444]
Perhaps this isn't solvable (or worth solving) until `use_extern_macros` is stabilizing, but I figured I'd open an issue to track it regardless.

With the following code on nightly:

```
#![feature(use_extern_macros)]

extern crate serde_json;

use serde_json::json;

fn main() {
    println!("{:?}", json!(1));
}
```

rustc complains that the `json_internal` macro is not in scope.

I expected the macro to be usable without additional imports.

**Comment by dtolnay** [comment]
This is a known limitation of the macro_rules macro system. I believe declarative macros 2.0 will fix this before `use_extern_macros` is stabilized. I have made an effort in the past to support individually importable macros but it is not worth doing given the current macro system. Thanks anyway!

**Comment by kamek-pf** [comment]
In case anyone else lands here, this is fixed as of 1.0.25

**Comment by dszvivian** [comment]
I am still facing the same error

is there any possible way i am going wrong 


main.rs
`
use serde_json::json;

fn main() {
    

    let value = json!({
                "name": "Bob",
                "age": 51,
                "address": {
                    "country": "Germany",
                    "city": "Example City",
                    "street": "Example Street"
                },
                "siblings": ["Alice", "Joe"]
            });


    println!("{:#?}",value);
}
`

`
[package]
name = "serdebasics"
version = "0.1.0"
edition = "2021"

[dependencies]

serde_json = "1.0"
`

**Comment by jumpnbrownweasel** [comment]
> I am still facing the same error

It's possible your Cargo.lock has an older version of serde 1.0.x pinned as in this [rust users thread](https://users.rust-lang.org/t/serde-json-issues-on-linux-json-macro/117534) .
