### ISSUE TITLE
u128 doesn't work for Value

### ISSUE THREAD

**Issue by alleycat-at-git** [serde-rs/json#502]
Looks like there's a bug in serde_json. This program:

```
#[macro_use]
extern crate serde_json;
use std::str::FromStr;

fn main() {
    let string = format!("{}", u128::max_value());
    println!("{}", string);
    let val = serde_json::value::Value::from_str(&string);
    let val2 = serde_json::to_value(u128::max_value());
    println!("{:#?}, {:#?}", val, val2);
}
```

outputs:

```
340282366920938463463374607431768211455
Ok(
    Number(
        340282366920938500000000000000000000000.0
    )
), Err(
    Error("u128 is not supported", line: 0, column: 0)
)
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=4b3d4b4c201c7a8dc5d3e4f93c1f8bae)

if you put arbitrary_precision feature, then Value works 100% without cutting precision, if you do it via `u128` => `String` => `Value`. However direct conversion `u128` => `Value` with `to_value` results in error.

**Comment by dtolnay** [comment]
Thanks! I would accept a PR to support u128 => Value in the case that arbitrary_precision is enabled.

**Comment by josecelano** [comment]
Hi, I'm getting the same error with this code:

```rust
use serde::Serialize;

extern crate serde_json;

#[derive(Serialize)]
struct Data {
    num: u128,
}

fn main() {
    println!("{}", serde_json::json!(Data { num: 1 }))
}
```

```s
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/serde-json-u128-bug`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("u128 is not supported", line: 0, column: 0)', src/main.rs:11:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Code: https://github.com/josecelano/serde-json-u128-bug/blob/main/src/main.rs

Using `serde` `1.0.152` and `serde_json` `1.0.91`:

```
[[package]]
name = "serde"
version = "1.0.152"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bb7d1f0d3021d347a83e556fc4683dea2ea09d87bccdf88ff5c12545d89d5efb"
dependencies = [
 "serde_derive",
]

[[package]]
name = "serde_json"
version = "1.0.91"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "877c235533714907a8c2464236f5c4b2a17262ef1bd71f38f35ea592c8da6883"
dependencies = [
 "itoa",
 "ryu",
 "serde",
]

**Comment by honeycomb-cheesecake** [comment]
I too am getting the `u128 is not supported` error when using `serde_json::from_str(...)` method. Similar struct layout to @josecelano above. Is it not supported?

**Comment by dtolnay** [comment]
Fixed in serde_json v1.0.93.

**Comment by honeycomb-cheesecake** [comment]
Hi, with serde_json v1.0.93 it's now working fine for serialisation, but when I use `let payload = serde_json::from_str::<MyType>(...);`, I'm still getting the u128 not supported error. Am I missing something? When I change to u64 it all works, so am I missing a setting?

**Comment by dtolnay** [comment]
Here is what I tried and it seems to work.

```rust
use serde::Deserialize;
use serde_json::json;

#[derive(Deserialize, Debug)]
pub struct Data {
    pub num: u128,
}

fn main() {
    let j = r#" {"num":1} "#;
    println!("{:?}", serde_json::from_str::<Data>(j).unwrap());

    let j = json!({"num": 1});
    println!("{:?}", serde_json::from_value::<Data>(j).unwrap());
}
```

**Comment by honeycomb-cheesecake** [comment]
Okay, so I did some digging and came up with the following. Is there a different handling when it comes to deserializing `enum`?

Works fine:

```rust
#[derive(Debug, serde::Deserialize)]
#[serde(rename = "a", tag = "type")]
struct A {
  test: u128
}

...
match serde_json::from_str::<A>(&text) {
  Ok(a) => {
    info!("{:#?}", a);
    info!("{:#?}", a.test);
  }
  Err(err) => {
    error!("{}", err.to_string());
  }
};

```

Fails with `u128 is not supported`:

```rust
#[derive(Debug, serde::Deserialize)]
#[serde(tag = "type")]
enum Opts {
    #[serde(rename = "a")]
    A { test: u128 },
}

...

match serde_json::from_str::<Opts>(&text) {
    Ok(Opts::A { test }) => {
        info!("{:#?}", test);
    }
    Err(err) => {
        error!("{}", err.to_string());
    }
};
```

**Comment by honeycomb-cheesecake** [comment]
Have I made a mistake somewhere? Any guidance would be much appreciated.

**Comment by jonasbb** [comment]
> Have I made a mistake somewhere? Any guidance would be much appreciated.

Internal tagging is implemented with buffering because the content could come before the tag. But the `Content` type does not support 128-bit values, and thus you see the error. See these other issues https://github.com/serde-rs/serde/issues/2230 and https://github.com/serde-rs/serde/issues/1183.
